name: CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.eslintrc.js'
      - '.prettierrc.json'
      - 'jest.config.js'
      - 'appsscript.json'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - '.vscode/**'
      - 'LICENSE'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'package-lock.json'
      - 'tsconfig.json'
      - '.eslintrc.js'
      - '.prettierrc.json'
      - 'jest.config.js'
      - 'appsscript.json'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - '.vscode/**'
      - 'LICENSE'

jobs:
  ci:
    runs-on: ubuntu-latest
    name: CI Check
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Cache node_modules
      uses: actions/cache@v4
      id: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
    
    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci
    
    - name: Check code formatting
      run: npm run format:check
    
    - name: Run ESLint
      run: npm run lint
    
    - name: Check TypeScript types
      run: npx tsc --noEmit
    
    - name: Run tests
      run: npm test
    
    - name: Build TypeScript
      run: npm run build
    
    - name: Run security audit
      run: |
        npm audit --audit-level=moderate || true
        echo "---"
        echo "Audit fix suggestions (dry-run):"
        npm audit fix --dry-run || true
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: build-output
        path: dist/